# Generated by Django 3.0.8 on 2020-09-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_name', models.CharField(db_index=True, max_length=20, verbose_name='Rubric Name')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
                'ordering': ['rubric_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='seed',
            options={'verbose_name': 'Seed', 'verbose_name_plural': 'Seeds'},
        ),
        migrations.RemoveField(
            model_name='seed',
            name='logn_description',
        ),
        migrations.AlterField(
            model_name='seed',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='short_description',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
